site_name: BizFlo 操作マニュアル
site_description: BizFlo 外部向けドキュメント
theme:
  name: material
  language: ja
  logo: images/favicon.png  # ロゴ画像のパス
  favicon: images/favicon.png  # ファビコン（ブラウザタブのアイコン）
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - content.code.copy
use_directory_urls: true
docs_dir: docs
site_dir: site

nav:
  - ホーム: index.md
  - ガイド:
      - 初期設定ガイド: initial-setup.md
      - 顧客管理: customer.md
      - 案件管理: project.md
      - KPI管理: kpi.md
      - 会計管理: accounting.md
      - 受発注管理: order.md
      - 運用・管理: operations.md
  - FAQ: faq.md
  - リリースノート: release-notes.md
  - 法務:
      - 利用規約: terms.md
      - プライバシーポリシー: privacy.md