name: Build & Deploy BizFlo Docs

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install MkDocs + theme
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.6.1 mkdocs-material==9.6.20 pymdown-extensions==10.16.1
      - name: Build MkDocs
        run: mkdocs build --strict
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
