name: Deploy BizFlo Docs
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install MkDocs + theme
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy to GitHub Pages (gh-pages branch)
        run: mkdocs gh-deploy --force --clean